export const PHASES = {
  STARTING: "STARTING",   
  NIGHT: "NIGHT",
  DAY_RESULT: "DAY_RESULT",
  DISCUSSION: "DISCUSSION",
  VOTING: "VOTING",
  ELIMINATION: "ELIMINATION",
  END_GAME: "END_GAME",
};